"""Gera output/auditoria.html com os 12 blocos aprovados."""
import datetime,html,json,os
from pathlib import Path
BASE=Path(__file__).resolve().parent.parent; OUT=BASE/'output'; BP=OUT/'boletim.json'; LP=OUT/'log_execucao.json'; AP=OUT/'auditoria.html'
PADRAO={'trabalhista-empresarial':'Radar Trabalhista Empresarial','direito-tributario':'Radar Tributário','societario-ma':'Radar Societário, Fusões e Aquisições','mercado-capitais-fundos':'Radar Mercado de Capitais e Fundos de Investimento','regulatorio-oleo-gas':'Radar Regulatório e Óleo e Gás','imobiliario-infraestrutura':'Radar Negócios Imobiliários e Infraestrutura','ambiental-esg':'Radar Ambiental e ESG','propriedade-intelectual':'Radar Propriedade Intelectual, Tecnologia e Privacidade','contencioso-civel':'Radar Solução de Conflitos'}
def e(v):return html.escape(str(v or ''),quote=True)
def load(p):
 with p.open(encoding='utf-8') as a:return json.load(a)
def table(headers,rows):
 if not rows:return '<p class="vazio">Nenhum registro nesta categoria.</p>'
 return '<div class="wrap"><table><thead><tr>'+''.join('<th>'+e(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in r)+'</tr>' for r in rows)+'</tbody></table></div>'
def sec(n,t,body,summary=''):return f'<section id="s{n}"><header><b>{n:02}</b><div><h2>{e(t)}</h2><small>{e(summary)}</small></div></header>{body}</section>'
def fontes(v):
 out=[]
 for x in v if isinstance(v,list) else []:
  out.append((str(x.get('fonte','')),str(x.get('motivo','')),str(x.get('reativar_em',''))) if isinstance(x,dict) else (str(x),'',''))
 return out
def main():
 b,l=load(BP),load(LP); c=b.get('boletins_config',{}); nomes=c.get('nomes_radares',{}); nr=lambda s:nomes.get(s,PADRAO.get(s,s)); fps=l.get('fontes_processadas',[]); fsr=fontes(b.get('fontes_sem_resultado',[])); fsp=fontes(b.get('fontes_sem_publicacao_hoje',[])); fet=fontes(b.get('fontes_com_erro_tecnico',[])); fd=fontes(c.get('fontes_em_defeso',[])); stats=b.get('estatisticas_por_boletim',{}); bl=l.get('resultado',{}).get('filtro1_bloqueios',{}); bd=l.get('filtro1_bloqueios_detalhe',{}); aud=b.get('auditoria',{}); rej=aud.get('rejeicoes_por_boletim',{}); pcs=aud.get('top_palavras_chave_detectadas',[]); sem=[x for x in b.get('itens',[]) if not x.get('boletins')]
 S=[]; S.append(sec(1,'Fontes processadas',table(['Fonte','Status','Caracteres'],[[e(x.get('fonte')),e(x.get('status')),e(x.get('tamanho_chars',''))] for x in fps]),f'{len(fps)} fontes')); S.append(sec(2,'Fontes sem resultado',table(['Fonte','Motivo'],[[e(a),e(m)] for a,m,_ in fsr]),f'{len(fsr)} fontes')); S.append(sec(3,'Fontes sem publicação',table(['Fonte','Motivo'],[[e(a),e(m)] for a,m,_ in fsp]),f'{len(fsp)} fontes')); S.append(sec(4,'Erros técnicos',table(['Fonte','Motivo'],[[e(a),e(m)] for a,m,_ in fet]),f'{len(fet)} fontes')); S.append(sec(5,'Fontes em defeso',table(['Fonte','Motivo','Retomada'],[[e(a),e(m),e(r)] for a,m,r in fd]),f'{len(fd)} fontes')); S.append(sec(6,'Totais por Radar',table(['Radar','Total'],[[e(nr(s)),e((stats.get(s,{}) or {}).get('total',0))] for s in PADRAO]))); S.append(sec(7,'Bloqueios do Filtro 1',table(['Radar','Quantidade'],[[e(nr(s)),e(q)] for s,q in bl.items() if q]),f"{aud.get('itens_com_bloqueio_f1',0)} itens")); S.append(sec(8,'Itens bloqueados',table(['Radar','Item'],[[e(nr(s)),e(t)] for s,ts in bd.items() for t in ts]),f'{sum(len(x) for x in bd.values())} registros')); S.append(sec(9,'Rejeições por Radar',table(['Radar','Rejeições'],[[e(nr(s)),e(rej.get(s,0))] for s in PADRAO]))); S.append(sec(10,'Principais palavras-chave',table(['Palavra-chave','Ocorrências'],[[e(x.get('palavra')),e(x.get('ocorrencias'))] for x in pcs]),f'{len(pcs)} termos')); S.append(sec(11,'Itens sem classificação',table(['Fonte','Item','Data'],[[e(x.get('fonte')),e(x.get('titulo')),e(x.get('data_publicacao'))] for x in sem]),f'{len(sem)} itens')); S.append(sec(12,'Páginas de validação','<div class="links">'+''.join(f'<a href="validacao_{s}.html">{e(nr(s))}</a>' for s in PADRAO)+'</div>','9 páginas'))
 doc='''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Auditoria dos Radares</title><style>body{margin:0;background:#f0f2f1;font-family:Arial;color:#1f2937}.page{max-width:1100px;margin:24px auto} .hero{background:#0d3320;color:white;padding:32px;border-radius:12px}section{background:white;margin:16px 0;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden}section>header{display:flex;gap:14px;padding:18px;background:#f8faf9}section>header>b{background:#0d3320;color:#fff;padding:9px;border-radius:6px}h2{margin:0;color:#0d3320}small{color:#6b7280}.wrap{overflow:auto;padding:18px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:9px;border-bottom:1px solid #e5e7eb}.vazio{padding:20px;text-align:center;color:#6b7280}.links{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:10px;padding:18px}.links a{padding:13px;border-left:4px solid #22c55e;color:#0d3320;text-decoration:none;background:#f8faf9}</style></head><body><main class="page"><div class="hero"><small>AUDITORIA CONSOLIDADA</small><h1>Auditoria dos Radares</h1></div>'''+''.join(S)+'</main></body></html>'; OUT.mkdir(exist_ok=True); tmp=AP.with_suffix('.html.tmp'); tmp.write_text(doc,encoding='utf-8'); os.replace(tmp,AP); print('Auditoria salva em',AP)
if __name__=='__main__':main()
